[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:sshd]
command=/usr/sbin/sshd -D
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd_err.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:ttyd]
command=ttyd --writable --port 7681 --credential student:%(ENV_STUDENT_PASSWORD)s /bin/bash --login
user=student
environment=HOME="/home/student"
directory=/home/student
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/ttyd.log
stderr_logfile=/var/log/supervisor/ttyd_err.log
